<a href="https://colab.research.google.com/github/HrushikeshAher/demo-repo2/blob/master/Numpy_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***NUMPY Library***


1.   Numpy provides efficient storage
2.   It also provides better ways to handle data for processing.
3.   NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.
4.   It is easy to learn.
5.   Numpy uses relatively less memory to store data.

***Sources:***
https://www.w3schools.com/python/numpy_intro.asp

***GITHUB***
https://github.com/numpy/numpy



In [1]:
import numpy as np

In [113]:
print(np.__version__)

1.19.5


**Array**



1.   Depending on size of numbers data type can be changed (int8,int16,int32.int64), there are also other types.
2.   Array creation methods(there are 5 methods)



**Array creation:** *Conversion from other Python structures (e.g., lists, tuples)*



In [34]:
myarr=np.array([[3,6,1000,7],[1,2,3,10]],np.int8) #Byte (-128 to 127)

In [42]:
myarr

array([[  3,   6, -24,   7],
       [  1,   2,   3,  10]], dtype=int8)

In [43]:
myarr.shape 

(2, 4)

In [44]:
myarr.dtype

dtype('int8')

In [45]:
myarr.ndim

2

**Array creation:** *Intrinsic numpy array creation objects (e.g., arange, ones, zeros, etc.)*




In [46]:
zeros=np.zeros((2,2))

In [51]:
zeros.shape 

(2, 2)

In [54]:
zeros.dtype

dtype('float64')

In [55]:
zeros.ndim

2

In [56]:
zeros

array([[0., 0.],
       [0., 0.]])

In [57]:
range_arr=np.arange(0,11,2)

In [58]:
range_arr

array([ 0,  2,  4,  6,  8, 10])

In [63]:
linspace_arr=np.linspace(1,100,4)

In [64]:
linspace_arr

array([  1.,  34.,  67., 100.])

In [65]:
empty_arr=np.empty((4,6))

In [66]:
empty_arr

array([[2.4822459e-316, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        0.0000000e+000, 0.0000000e+000]])

In [67]:
empty_like=np.empty_like(linspace_arr)

In [68]:
empty_like

array([  1.,  34.,  67., 100.])

In [69]:
ide_arr=np.identity(10)

In [70]:
ide_arr

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [71]:
ide_arr= ide_arr.reshape(5,20) # Reshaping array

In [72]:
ide_arr

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1.]])

In [74]:
ide_arr=ide_arr.ravel() #convert into 1D array

In [75]:
ide_arr.shape

(100,)

**NUMPY AXIS**

In [95]:
x=[[1,2,3],[4,5,100],[7,8,9]]

In [96]:
arr_x=np.array(x)

In [78]:
arr_x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
arr_x.sum(axis=0) #adds according to axis

array([12, 15, 18])

In [81]:
arr_x.sum(axis=1) #adds according to axis

array([ 6, 15, 24])

In [83]:
arr_x.T #Transpose the array i.e. convert rows to columns and columns to rows

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [84]:
arr_x.flat ##converts into iterable object

In [85]:
for i in arr_x.flat:
  print(i)

1
2
3
4
5
6
7
8
9


In [86]:
arr_x.ndim

2

In [87]:
arr_x.size

9

In [88]:
arr_x.nbytes

72

In [97]:
arr_x.argmax() ## returns index of max element

5

In [98]:
arr_x.argmin()

0

In [99]:
arr_x.ravel().argsort() ## returns index of sorted array

array([0, 1, 2, 3, 4, 6, 7, 8, 5])

In [100]:
metrix_1=np.array([[1,2],[3,4]])

In [101]:
metrix_2=np.array([[5,6],[7,8]])

In [102]:
metrix_1+metrix_2

array([[ 6,  8],
       [10, 12]])

In [103]:
metrix_1*metrix_2

array([[ 5, 12],
       [21, 32]])

In [105]:
np.sqrt(metrix_1)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [106]:
np.square(metrix_1) #SUM,MIN,MAX

array([[ 1,  4],
       [ 9, 16]])

In [108]:
np.where(metrix_1>1)

(array([0, 1, 1]), array([1, 0, 1]))

In [109]:
np.count_nonzero(arr_x)

9

In [112]:
np.nonzero(arr_x)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [114]:
print(type(arr_x))

<class 'numpy.ndarray'>
